version: "3"

services:

  db:
    environment:
      POSTGRES_USER: "roadini"
      POSTGRES_DB: "geoclust"
      POSTGRES_PASSWORD: "demo1234"
    image: "kartoza/postgis:9.6-2.4"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  api:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    links:
      - db
    # diesel infer_schema macro gives warnings with this flag.
    # environment:
    #   - CARGO_INCREMENTAL=1
    environment:
      DATABASE_URL: "postgres://roadini:demo1234@db/geoclust"
    command: bash -c "bash ./wait-for-it.sh db:5432 -q -- diesel setup && cargo watch -x run"

# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
  pgdata: {}
